sudo: required
language: node_js

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

jobs:
  include:
    - stage: Build
      script:
        - yarn lint
        - yarn build
      node_js: "8"
    - script:
        - yarn lint
        - yarn build
      node_js: "10"